# Generated by Django 5.1.4 on 2025-01-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
