# Generated by Django 5.1.4 on 2025-01-23 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_categoery'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ctry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.categoery'),
        ),
    ]
