# Generated by Django 5.1.4 on 2025-02-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_products_image_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoery',
            new_name='Category',
        ),
    ]
